### PR TITLE
[doc]: add a note about removing staging certs before moving to production.

### PR DESCRIPTION
**Pull request by fredrikekre**

### CODE REVIEW

**Comment by fredrikekre** [comment]
(Alternatively I suppose any staging certificates could be ignored if `STAGING=0` so that `certbot` request new certs anyway, but that is probably a bit too clever.)

**Comment by JonasAlfredsson** [comment]
This is a good note, but could you perhaps include something about that you can do a [force renew](https://github.com/JonasAlfredsson/docker-nginx-certbot/blob/master/docs/advanced_usage.md#manualforce-renewal) the achieve the same thing?

**Comment by fredrikekre** [comment]
Done,.

**Comment by JonasAlfredsson** [comment]
Thank you for this :)

**Pull request merged**
